### ISSUE TITLE
发现部分被识别为Pixel但仍会占用空间的机型额外修改build.prop中的机型后上传就不再占用空间

### ISSUE THREAD

**Issue by wydy** [ZeroSimple/Pixel-2016-Permissions#3]
在Xperia XZ1上测试通过，感觉可以把这个功能合并进模块，缺点就是手机以后都会被识别为Pixel

**Comment by ButaiKirin** [comment]
收到。我测试一下

**Comment by wydy** [comment]
> 收到。我测试一下

不一定准确，感觉有可能是因为今天谷歌的空间占用信息更新有延迟

**Comment by ButaiKirin** [comment]
> > 收到。我测试一下
> 
> 不一定准确，感觉有可能是因为今天谷歌的空间占用信息更新有延迟

确实，测试了似乎没效果。测试机型也是索尼XZ1
