### ISSUE TITLE
magisk本地安装报错

### ISSUE THREAD

**Issue by Jakob-Boy** [ZeroSimple/Pixel-2016-Permissions#4]
提示unzip error，是下载release中的zip嘛？

**Comment by ButaiKirin** [comment]
是下载release中的Pixel_2016_Permissions.zip，请检查网络情况，保证下载完整。
MD5: 197fce9177d1a373db60c2c0ce0b0bee

**Comment by Jakob-Boy** [comment]
ok，从vps下载校验一致，本地下载md5值不同（震惊
感谢回复！

**Comment by ButaiKirin** [comment]
> ok，从vps下载校验一致，本地下载md5值不同（震惊
> 感谢回复！

中国对GitHub尤其是下载内容有污染，经常出错。建议挂梯或者使用FastGit.org
